hydra:
  output_subdir: null
  run:  
    dir: .
data:
  task: binary
  num_pos: 5
  num_neg: 5
para:
  ori: false
  dropout: 0.5
  loss_alpha: 1.0
  loss_beta: 1.0
opt:
  name: Adam
  lr: 0.0007
  weight_decay: 5e-05
sche:
  name: SVFENDLR
num_epoch: 5
batch_size: 128
seed: 2024
model: SVFEND
dataset: FakeTT
type: default
patience: 3
name: SVFEND